# Generated by Django 5.2.7 on 2025-11-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="descritpion",
            new_name="description",
        ),
    ]
