# Generated by Django 5.2.7 on 2025-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_descritpion_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
